### ISSUE TITLE
Conflict with `Windows.h`

### ISSUE THREAD

**Issue by MartinKoch123** [Tessil/ordered-map#35]
Hello, the following does not compile with VS2019:

```
#include <Windows.h>
#include <ordered_map.h>
int main() {}
```

![grafik](https://user-images.githubusercontent.com/61880738/140928232-92c429ab-1489-4997-bf5b-1b2e67ea034b.png)

Switching the include order works however. Im not a C++ expert but it seemed worth pointing out.

**Comment by Tessil** [comment]
Hello,

It's due to `Windows.h` that historically defines `min`/`max` macros which are incompatible with the C++ standard. The best way is to define the `NOMINMAX` macro. See https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std for details.
